//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncLackingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public long id { get; set; }
        public string label_1 { get; set; }
        public string label_2 { get; set; }
        public string label_3 { get; set; }
        public long order_id { get; set; }
    
        public virtual orders orders { get; set; }
    }
}
