//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncLackingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp1
    {
        public string PO { get; set; }
        public string Model_name { get; set; }
        public string 物料 { get; set; }
        public Nullable<double> 缺料數量 { get; set; }
        public string UnitsInStock { get; set; }
        public string 物管 { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
