//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncLackingData
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp1_Log
    {
        public int id { get; set; }
        public string po { get; set; }
        public string modelName { get; set; }
        public string material { get; set; }
        public Nullable<double> shortage { get; set; }
        public string unitsInStock { get; set; }
        public string owner { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
    }
}
